import { NextResponse } from "next/server";

// Comprehensive in-memory storage for fireplace manuals
// Includes Majestic, Regency, Napoleon, Heat & Glo, Vermont Castings, Dimplex and more
let manuals: Manual[] = [
  // ============================================
  // MAJESTIC PRODUCTS - Full Product Line
  // ============================================
  
  // Majestic Direct Vent Fireplaces - DV Series
  {
    id: "m-001",
    brand: "Majestic",
    model: "DVLL36",
    type: "Direct Vent Linear Fireplace",
    fileName: "Majestic_DVLL36_Manual.pdf",
    pages: 48,
    uploadDate: "2025-02-26",
    category: "Direct Vent",
  },
  {
    id: "m-002",
    brand: "Majestic",
    model: "DVLL42",
    type: "Direct Vent Linear Fireplace",
    fileName: "Majestic_DVLL42_Manual.pdf",
    pages: 52,
    uploadDate: "2025-02-26",
    category: "Direct Vent",
  },
  {
    id: "m-003",
    brand: "Majestic",
    model: "DVLL54",
    type: "Direct Vent Linear Fireplace",
    fileName: "Majestic_DVLL54_Manual.pdf",
    pages: 56,
    uploadDate: "2025-02-26",
    category: "Direct Vent",
  },
  {
    id: "m-004",
    brand: "Majestic",
    model: "DVCT36",
    type: "Direct Vent Corner Fireplace",
    fileName: "Majestic_DVCT36_Manual.pdf",
    pages: 44,
    uploadDate: "2025-02-26",
    category: "Direct Vent",
  },
  {
    id: "m-005",
    brand: "Majestic",
    model: "DVCT42",
    type: "Direct Vent Corner Fireplace",
    fileName: "Majestic_DVCT42_Manual.pdf",
    pages: 48,
    uploadDate: "2025-02-26",
    category: "Direct Vent",
  },
  {
    id: "m-006",
    brand: "Majestic",
    model: "DVG36",
    type: "Direct Vent Gas Fireplace",
    fileName: "Majestic_DVG36_Manual.pdf",
    pages: 40,
    uploadDate: "2025-02-26",
    category: "Direct Vent",
  },
  {
    id: "m-007",
    brand: "Majestic",
    model: "DVG42",
    type: "Direct Vent Gas Fireplace",
    fileName: "Majestic_DVG42_Manual.pdf",
    pages: 44,
    uploadDate: "2025-02-26",
    category: "Direct Vent",
  },
  {
    id: "m-008",
    brand: "Majestic",
    model: "DVSL36",
    type: "Direct Vent See-Through Fireplace",
    fileName: "Majestic_DVSL36_Manual.pdf",
    pages: 46,
    uploadDate: "2025-02-26",
    category: "Direct Vent",
  },
  {
    id: "m-009",
    brand: "Majestic",
    model: "DVSL42",
    type: "Direct Vent See-Through Fireplace",
    fileName: "Majestic_DVSL42_Manual.pdf",
    pages: 50,
    uploadDate: "2025-02-26",
    category: "Direct Vent",
  },
  
  // Majestic B-Vent Fireplaces
  {
    id: "m-010",
    brand: "Majestic",
    model: "BFDV36",
    type: "B-Vent Direct Vent Fireplace",
    fileName: "Majestic_BFDV36_Manual.pdf",
    pages: 38,
    uploadDate: "2025-02-26",
    category: "B-Vent",
  },
  {
    id: "m-011",
    brand: "Majestic",
    model: "BFDV42",
    type: "B-Vent Direct Vent Fireplace",
    fileName: "Majestic_BFDV42_Manual.pdf",
    pages: 42,
    uploadDate: "2025-02-26",
    category: "B-Vent",
  },
  {
    id: "m-012",
    brand: "Majestic",
    model: "BV36",
    type: "B-Vent Fireplace",
    fileName: "Majestic_BV36_Manual.pdf",
    pages: 36,
    uploadDate: "2025-02-26",
    category: "B-Vent",
  },
  {
    id: "m-013",
    brand: "Majestic",
    model: "BV42",
    type: "B-Vent Fireplace",
    fileName: "Majestic_BV42_Manual.pdf",
    pages: 40,
    uploadDate: "2025-02-26",
    category: "B-Vent",
  },
  
  // Majestic Standard Gas Fireplaces - Q Series
  {
    id: "m-014",
    brand: "Majestic",
    model: "QBDM36",
    type: "Dual Fuel Fireplace",
    fileName: "Majestic_QBDM36_Manual.pdf",
    pages: 32,
    uploadDate: "2025-02-26",
    category: "Dual Fuel",
  },
  {
    id: "m-015",
    brand: "Majestic",
    model: "QCB36",
    type: "Convertible Box Fireplace",
    fileName: "Majestic_QCB36_Manual.pdf",
    pages: 34,
    uploadDate: "2025-02-26",
    category: "Gas Fireplaces",
  },
  {
    id: "m-016",
    brand: "Majestic",
    model: "QCF36",
    type: "Corner Fireplace",
    fileName: "Majestic_QCF36_Manual.pdf",
    pages: 36,
    uploadDate: "2025-02-26",
    category: "Gas Fireplaces",
  },
  {
    id: "m-017",
    brand: "Majestic",
    model: "QLD36",
    type: "Louvred Fireplace",
    fileName: "Majestic_QLD36_Manual.pdf",
    pages: 32,
    uploadDate: "2025-02-26",
    category: "Gas Fireplaces",
  },
  {
    id: "m-018",
    brand: "Majestic",
    model: "QLD42",
    type: "Louvred Fireplace",
    fileName: "Majestic_QLD42_Manual.pdf",
    pages: 34,
    uploadDate: "2025-02-26",
    category: "Gas Fireplaces",
  },
  
  // Majestic 36BDV Series
  {
    id: "m-019",
    brand: "Majestic",
    model: "36BDV",
    type: "Direct Vent Fireplace",
    fileName: "Majestic_36BDV_Manual.pdf",
    pages: 28,
    uploadDate: "2025-02-26",
    category: "Direct Vent",
  },
  {
    id: "m-020",
    brand: "Majestic",
    model: "42BDV",
    type: "Direct Vent Fireplace",
    fileName: "Majestic_42BDV_Manual.pdf",
    pages: 30,
    uploadDate: "2025-02-26",
    category: "Direct Vent",
  },
  
  // Majestic Ruby Series
  {
    id: "m-021",
    brand: "Majestic",
    model: "Ruby 36",
    type: "Gas Fireplace",
    fileName: "Majestic_Ruby36_Manual.pdf",
    pages: 40,
    uploadDate: "2025-02-26",
    category: "Gas Fireplaces",
  },
  {
    id: "m-022",
    brand: "Majestic",
    model: "Ruby 42",
    type: "Gas Fireplace",
    fileName: "Majestic_Ruby42_Manual.pdf",
    pages: 44,
    uploadDate: "2025-02-26",
    category: "Gas Fireplaces",
  },
  
  // Majestic Meridian Series
  {
    id: "m-023",
    brand: "Majestic",
    model: "Meridian",
    type: "Gas Fireplace",
    fileName: "Majestic_Meridian_Manual.pdf",
    pages: 36,
    uploadDate: "2025-02-26",
    category: "Gas Fireplaces",
  },
  {
    id: "m-024",
    brand: "Majestic",
    model: "Meridian N",
    type: "Gas Fireplace",
    fileName: "Majestic_MeridianN_Manual.pdf",
    pages: 38,
    uploadDate: "2025-02-26",
    category: "Gas Fireplaces",
  },
  
  // Majestic Avalon Series
  {
    id: "m-025",
    brand: "Majestic",
    model: "Avalon 36",
    type: "Gas Fireplace",
    fileName: "Majestic_Avalon36_Manual.pdf",
    pages: 40,
    uploadDate: "2025-02-26",
    category: "Gas Fireplaces",
  },
  {
    id: "m-026",
    brand: "Majestic",
    model: "Avalon 42",
    type: "Gas Fireplace",
    fileName: "Majestic_Avalon42_Manual.pdf",
    pages: 44,
    uploadDate: "2025-02-26",
    category: "Gas Fireplaces",
  },
  {
    id: "m-027",
    brand: "Majestic",
    model: "Avalon 50",
    type: "Gas Fireplace",
    fileName: "Majestic_Avalon50_Manual.pdf",
    pages: 48,
    uploadDate: "2025-02-26",
    category: "Gas Fireplaces",
  },
  
  // Majestic Bronze Fireplace
  {
    id: "m-028",
    brand: "Majestic",
    model: "Bronze Fireplace",
    type: "Gas Fireplace",
    fileName: "Majestic_Bronze_Manual.pdf",
    pages: 38,
    uploadDate: "2025-02-26",
    category: "Gas Fireplaces",
  },
  
  // Majestic 8000 Series
  {
    id: "m-029",
    brand: "Majestic",
    model: "8000 Series",
    type: "Gas Fireplace",
    fileName: "Majestic_8000Series_Manual.pdf",
    pages: 44,
    uploadDate: "2025-02-26",
    category: "Gas Fireplaces",
  },
  {
    id: "m-030",
    brand: "Majestic",
    model: "8500 Series",
    type: "Gas Fireplace",
    fileName: "Majestic_8500Series_Manual.pdf",
    pages: 46,
    uploadDate: "2025-02-26",
    category: "Gas Fireplaces",
  },
  {
    id: "m-031",
    brand: "Majestic",
    model: "9000 Series",
    type: "Gas Fireplace",
    fileName: "Majestic_9000Series_Manual.pdf",
    pages: 48,
    uploadDate: "2025-02-26",
    category: "Gas Fireplaces",
  },
  
  // Majestic DCV Series
  {
    id: "m-032",
    brand: "Majestic",
    model: "DCV36",
    type: "Direct Vent Fireplace",
    fileName: "Majestic_DCV36_Manual.pdf",
    pages: 30,
    uploadDate: "2025-02-26",
    category: "Direct Vent",
  },
  {
    id: "m-033",
    brand: "Majestic",
    model: "DCV42",
    type: "Direct Vent Fireplace",
    fileName: "Majestic_DCV42_Manual.pdf",
    pages: 32,
    uploadDate: "2025-02-26",
    category: "Direct Vent",
  },
  
  // Majestic SL Series (from jobs data)
  {
    id: "m-034",
    brand: "Majestic",
    model: "SL-600",
    type: "Gas Fireplace",
    fileName: "Majestic_SL600_Manual.pdf",
    pages: 36,
    uploadDate: "2025-02-26",
    category: "Gas Fireplaces",
  },
  {
    id: "m-035",
    brand: "Majestic",
    model: "SL-700",
    type: "Gas Fireplace",
    fileName: "Majestic_SL700_Manual.pdf",
    pages: 38,
    uploadDate: "2025-02-26",
    category: "Gas Fireplaces",
  },
  {
    id: "m-036",
    brand: "Majestic",
    model: "SL-900",
    type: "Gas Fireplace",
    fileName: "Majestic_SL900_Manual.pdf",
    pages: 40,
    uploadDate: "2025-02-26",
    category: "Gas Fireplaces",
  },
  
  // Majestic Electric Fireplaces - SLE Series
  {
    id: "m-037",
    brand: "Majestic",
    model: "SLE18",
    type: "Electric Fireplace",
    fileName: "Majestic_SLE18_Manual.pdf",
    pages: 24,
    uploadDate: "2025-02-26",
    category: "Electric",
  },
  {
    id: "m-038",
    brand: "Majestic",
    model: "SLE24",
    type: "Electric Fireplace",
    fileName: "Majestic_SLE24_Manual.pdf",
    pages: 26,
    uploadDate: "2025-02-26",
    category: "Electric",
  },
  {
    id: "m-039",
    brand: "Majestic",
    model: "SLE30",
    type: "Electric Fireplace",
    fileName: "Majestic_SLE30_Manual.pdf",
    pages: 28,
    uploadDate: "2025-02-26",
    category: "Electric",
  },
  {
    id: "m-040",
    brand: "Majestic",
    model: "SLE36",
    type: "Electric Fireplace",
    fileName: "Majestic_SLE36_Manual.pdf",
    pages: 30,
    uploadDate: "2025-02-26",
    category: "Electric",
  },
  
  // Majestic Wood Stoves
  {
    id: "m-041",
    brand: "Majestic",
    model: "SHAWNEE",
    type: "Wood Stove",
    fileName: "Majestic_Shawnee_Manual.pdf",
    pages: 32,
    uploadDate: "2025-02-26",
    category: "Wood Stoves",
  },
  {
    id: "m-042",
    brand: "Majestic",
    model: "Bristol",
    type: "Wood Stove",
    fileName: "Majestic_Bristol_Manual.pdf",
    pages: 34,
    uploadDate: "2025-02-26",
    category: "Wood Stoves",
  },
  {
    id: "m-043",
    brand: "Majestic",
    model: "Welch",
    type: "Wood Stove",
    fileName: "Majestic_Welch_Manual.pdf",
    pages: 30,
    uploadDate: "2025-02-26",
    category: "Wood Stoves",
  },
  {
    id: "m-044",
    brand: "Majestic",
    model: "Monroe",
    type: "Wood Stove",
    fileName: "Majestic_Monroe_Manual.pdf",
    pages: 28,
    uploadDate: "2025-02-26",
    category: "Wood Stoves",
  },
  
  // Majestic Fireplace Inserts
  {
    id: "m-045",
    brand: "Majestic",
    model: "IDV30",
    type: "Insert Direct Vent",
    fileName: "Majestic_IDV30_Manual.pdf",
    pages: 38,
    uploadDate: "2025-02-26",
    category: "Inserts",
  },
  {
    id: "m-046",
    brand: "Majestic",
    model: "IDV40",
    type: "Insert Direct Vent",
    fileName: "Majestic_IDV40_Manual.pdf",
    pages: 42,
    uploadDate: "2025-02-26",
    category: "Inserts",
  },
  {
    id: "m-047",
    brand: "Majestic",
    model: "MDV30",
    type: "Multi-Direct Vent Insert",
    fileName: "Majestic_MDV30_Manual.pdf",
    pages: 40,
    uploadDate: "2025-02-26",
    category: "Inserts",
  },
  {
    id: "m-048",
    brand: "Majestic",
    model: "MDV40",
    type: "Multi-Direct Vent Insert",
    fileName: "Majestic_MDV40_Manual.pdf",
    pages: 44,
    uploadDate: "2025-02-26",
    category: "Inserts",
  },
  
  // Majestic Outdoor Fireplaces
  {
    id: "m-049",
    brand: "Majestic",
    model: "Outdoor Fireplace OCF",
    type: "Outdoor Fireplace",
    fileName: "Majestic_OCF_Manual.pdf",
    pages: 28,
    uploadDate: "2025-02-26",
    category: "Outdoor",
  },
  {
    id: "m-050",
    brand: "Majestic",
    model: "Outdoor Plus Series",
    type: "Outdoor Fireplace",
    fileName: "Majestic_OutdoorPlus_Manual.pdf",
    pages: 32,
    uploadDate: "2025-02-26",
    category: "Outdoor",
  },
  
  // Majestic Trilogy Series
  {
    id: "m-051",
    brand: "Majestic",
    model: "Trilogy 36",
    type: "Tri-Vent Fireplace",
    fileName: "Majestic_Trilogy36_Manual.pdf",
    pages: 42,
    uploadDate: "2025-02-26",
    category: "Gas Fireplaces",
  },
  {
    id: "m-052",
    brand: "Majestic",
    model: "Trilogy 42",
    type: "Tri-Vent Fireplace",
    fileName: "Majestic_Trilogy42_Manual.pdf",
    pages: 46,
    uploadDate: "2025-02-26",
    category: "Gas Fireplaces",
  },
  
  // ============================================
  // OTHER BRANDS
  // ============================================
  
  // Regency Fireplaces
  {
    id: "r-001",
    brand: "Regency",
    model: "F1100",
    type: "Gas Insert",
    fileName: "Regency_F1100_Manual.pdf",
    pages: 48,
    uploadDate: "2025-01-15",
    category: "Gas Inserts",
  },
  {
    id: "r-002",
    brand: "Regency",
    model: "F5100",
    type: "Gas Insert",
    fileName: "Regency_F5100_Manual.pdf",
    pages: 52,
    uploadDate: "2025-01-15",
    category: "Gas Inserts",
  },
  {
    id: "r-003",
    brand: "Regency",
    model: "HZ40E",
    type: "Gas Fireplace",
    fileName: "Regency_HZ40E_Manual.pdf",
    pages: 44,
    uploadDate: "2025-01-15",
    category: "Gas Fireplaces",
  },
  {
    id: "r-004",
    brand: "Regency",
    model: "HZ50E",
    type: "Gas Fireplace",
    fileName: "Regency_HZ50E_Manual.pdf",
    pages: 46,
    uploadDate: "2025-01-15",
    category: "Gas Fireplaces",
  },
  {
    id: "r-005",
    brand: "Regency",
    model: "U29",
    type: "Wood Stove",
    fileName: "Regency_U29_Manual.pdf",
    pages: 40,
    uploadDate: "2025-01-15",
    category: "Wood Stoves",
  },
  {
    id: "r-006",
    brand: "Regency",
    model: "C3",
    type: "Pellet Stove",
    fileName: "Regency_C3_Manual.pdf",
    pages: 36,
    uploadDate: "2025-01-15",
    category: "Pellet Stoves",
  },
  
  // Napoleon Fireplaces
  {
    id: "n-001",
    brand: "Napoleon",
    model: "AS35",
    type: "Gas Stove",
    fileName: "Napoleon_AS35_Manual.pdf",
    pages: 36,
    uploadDate: "2025-01-10",
    category: "Gas Stoves",
  },
  {
    id: "n-002",
    brand: "Napoleon",
    model: "T450",
    type: "Gas Fireplace",
    fileName: "Napoleon_T450_Manual.pdf",
    pages: 42,
    uploadDate: "2025-01-10",
    category: "Gas Fireplaces",
  },
  {
    id: "n-003",
    brand: "Napoleon",
    model: "T500",
    type: "Gas Fireplace",
    fileName: "Napoleon_T500_Manual.pdf",
    pages: 44,
    uploadDate: "2025-01-10",
    category: "Gas Fireplaces",
  },
  {
    id: "n-004",
    brand: "Napoleon",
    model: "X450",
    type: "Electric Fireplace",
    fileName: "Napoleon_X450_Manual.pdf",
    pages: 28,
    uploadDate: "2025-01-10",
    category: "Electric",
  },
  {
    id: "n-005",
    brand: "Napoleon",
    model: "X500",
    type: "Electric Fireplace",
    fileName: "Napoleon_X500_Manual.pdf",
    pages: 30,
    uploadDate: "2025-01-10",
    category: "Electric",
  },
  
  // Heat & Glo
  {
    id: "hg-001",
    brand: "Heat & Glo",
    model: "SLR",
    type: "Gas Fireplace",
    fileName: "HeatGlo_SLR_Manual.pdf",
    pages: 52,
    uploadDate: "2025-01-08",
    category: "Gas Fireplaces",
  },
  {
    id: "hg-002",
    brand: "Heat & Glo",
    model: "SLR-II",
    type: "Gas Fireplace",
    fileName: "HeatGlo_SLRII_Manual.pdf",
    pages: 48,
    uploadDate: "2025-01-08",
    category: "Gas Fireplaces",
  },
  {
    id: "hg-003",
    brand: "Heat & Glo",
    model: "6000CLX",
    type: "Gas Fireplace",
    fileName: "HeatGlo_6000CLX_Manual.pdf",
    pages: 44,
    uploadDate: "2025-01-08",
    category: "Gas Fireplaces",
  },
  {
    id: "hg-004",
    brand: "Heat & Glo",
    model: "8000CLX",
    type: "Gas Fireplace",
    fileName: "HeatGlo_8000CLX_Manual.pdf",
    pages: 46,
    uploadDate: "2025-01-08",
    category: "Gas Fireplaces",
  },
  {
    id: "hg-005",
    brand: "Heat & Glo",
    model: "Gemini",
    type: "Gas Fireplace",
    fileName: "HeatGlo_Gemini_Manual.pdf",
    pages: 50,
    uploadDate: "2025-01-08",
    category: "Gas Fireplaces",
  },
  
  // Vermont Castings
  {
    id: "vc-001",
    brand: "Vermont Castings",
    model: "Defiant",
    type: "Wood Stove",
    fileName: "VC_Defiant_Manual.pdf",
    pages: 44,
    uploadDate: "2024-12-20",
    category: "Wood Stoves",
  },
  {
    id: "vc-002",
    brand: "Vermont Castings",
    model: "Resolute",
    type: "Wood Stove",
    fileName: "VC_Resolute_Manual.pdf",
    pages: 40,
    uploadDate: "2024-12-20",
    category: "Wood Stoves",
  },
  {
    id: "vc-003",
    brand: "Vermont Castings",
    model: "Intrepid",
    type: "Wood Stove",
    fileName: "VC_Intrepid_Manual.pdf",
    pages: 38,
    uploadDate: "2024-12-20",
    category: "Wood Stoves",
  },
  {
    id: "vc-004",
    brand: "Vermont Castings",
    model: "Majestic",
    type: "Wood Stove",
    fileName: "VC_Majestic_Manual.pdf",
    pages: 42,
    uploadDate: "2024-12-20",
    category: "Wood Stoves",
  },
  
  // Dimplex
  {
    id: "d-001",
    brand: "Dimplex",
    model: "Opti-Myst",
    type: "Electric Fireplace",
    fileName: "Dimplex_OptiMyst_Manual.pdf",
    pages: 28,
    uploadDate: "2024-12-15",
    category: "Electric",
  },
  {
    id: "d-002",
    brand: "Dimplex",
    model: "Opti-V",
    type: "Electric Fireplace",
    fileName: "Dimplex_OptiV_Manual.pdf",
    pages: 26,
    uploadDate: "2024-12-15",
    category: "Electric",
  },
  {
    id: "d-003",
    brand: "Dimplex",
    model: "Revillusion",
    type: "Electric Fireplace",
    fileName: "Dimplex_Revillusion_Manual.pdf",
    pages: 30,
    uploadDate: "2024-12-15",
    category: "Electric",
  },
  {
    id: "d-004",
    brand: "Dimplex",
    model: "Linear",
    type: "Electric Fireplace",
    fileName: "Dimplex_Linear_Manual.pdf",
    pages: 24,
    uploadDate: "2024-12-15",
    category: "Electric",
  },
  
  // Travis Industries
  {
    id: "t-001",
    brand: "Travis",
    model: "LW1100",
    type: "Wood Stove",
    fileName: "Travis_LW1100_Manual.pdf",
    pages: 36,
    uploadDate: "2024-12-10",
    category: "Wood Stoves",
  },
  {
    id: "t-002",
    brand: "Travis",
    model: "Lopi",
    type: "Wood Stove",
    fileName: "Travis_Lopi_Manual.pdf",
    pages: 38,
    uploadDate: "2024-12-10",
    category: "Wood Stoves",
  },
  {
    id: "t-003",
    brand: "Travis",
    model: "Apex",
    type: "Gas Fireplace",
    fileName: "Travis_Apex_Manual.pdf",
    pages: 42,
    uploadDate: "2024-12-10",
    category: "Gas Fireplaces",
  },
  
  // Quadra-Fire
  {
    id: "q-001",
    brand: "Quadra-Fire",
    model: "Santa Fe",
    type: "Wood Stove",
    fileName: "QuadraFire_SantaFe_Manual.pdf",
    pages: 40,
    uploadDate: "2024-12-05",
    category: "Wood Stoves",
  },
  {
    id: "q-002",
    brand: "Quadra-Fire",
    model: "Explorer",
    type: "Pellet Stove",
    fileName: "QuadraFire_Explorer_Manual.pdf",
    pages: 44,
    uploadDate: "2024-12-05",
    category: "Pellet Stoves",
  },
  {
    id: "q-003",
    brand: "Quadra-Fire",
    model: "Denali",
    type: "Pellet Stove",
    fileName: "QuadraFire_Denali_Manual.pdf",
    pages: 46,
    uploadDate: "2024-12-05",
    category: "Pellet Stoves",
  },
  
  // Harman
  {
    id: "h-001",
    brand: "Harman",
    model: "P68",
    type: "Pellet Stove",
    fileName: "Harman_P68_Manual.pdf",
    pages: 48,
    uploadDate: "2024-12-01",
    category: "Pellet Stoves",
  },
  {
    id: "h-002",
    brand: "Harman",
    model: "Trophy",
    type: "Pellet Stove",
    fileName: "Harman_Trophy_Manual.pdf",
    pages: 44,
    uploadDate: "2024-12-01",
    category: "Pellet Stoves",
  },
  {
    id: "h-003",
    brand: "Harman",
    model: "Advance",
    type: "Pellet Stove",
    fileName: "Harman_Advance_Manual.pdf",
    pages: 46,
    uploadDate: "2024-12-01",
    category: "Pellet Stoves",
  },
  
  // Buck Stove
  {
    id: "b-001",
    brand: "Buck Stove",
    model: "Model 20",
    type: "Wood Stove",
    fileName: "BuckStove_Model20_Manual.pdf",
    pages: 32,
    uploadDate: "2024-11-25",
    category: "Wood Stoves",
  },
  {
    id: "b-002",
    brand: "Buck Stove",
    model: "Model 24",
    type: "Wood Stove",
    fileName: "BuckStove_Model24_Manual.pdf",
    pages: 34,
    uploadDate: "2024-11-25",
    category: "Wood Stoves",
  },
  {
    id: "b-003",
    brand: "Buck Stove",
    model: "Model 27",
    type: "Wood Stove",
    fileName: "BuckStove_Model27_Manual.pdf",
    pages: 36,
    uploadDate: "2024-11-25",
    category: "Wood Stoves",
  },
  {
    id: "b-004",
    brand: "Buck Stove",
    model: "Model 91",
    type: "Wood Stove",
    fileName: "BuckStove_Model91_Manual.pdf",
    pages: 38,
    uploadDate: "2024-11-25",
    category: "Wood Stoves",
  },
  
  // Pacific Energy
  {
    id: "pe-001",
    brand: "Pacific Energy",
    model: "Alderlea",
    type: "Wood Stove",
    fileName: "PacificEnergy_Alderlea_Manual.pdf",
    pages: 36,
    uploadDate: "2024-11-20",
    category: "Wood Stoves",
  },
  {
    id: "pe-002",
    brand: "Pacific Energy",
    model: "Summit",
    type: "Wood Stove",
    fileName: "PacificEnergy_Summit_Manual.pdf",
    pages: 38,
    uploadDate: "2024-11-20",
    category: "Wood Stoves",
  },
  {
    id: "pe-003",
    brand: "Pacific Energy",
    model: "Fireview",
    type: "Wood Stove",
    fileName: "PacificEnergy_Fireview_Manual.pdf",
    pages: 34,
    uploadDate: "2024-11-20",
    category: "Wood Stoves",
  },
  
  // Stove Builder International (SBI)
  {
    id: "sbi-001",
    brand: "SBI",
    model: "Enerzone",
    type: "Wood Stove",
    fileName: "SBI_Enerzone_Manual.pdf",
    pages: 40,
    uploadDate: "2024-11-15",
    category: "Wood Stoves",
  },
  {
    id: "sbi-002",
    brand: "SBI",
    model: "Drolet",
    type: "Wood Stove",
    fileName: "SBI_Drolet_Manual.pdf",
    pages: 36,
    uploadDate: "2024-11-15",
    category: "Wood Stoves",
  },
  {
    id: "sbi-003",
    brand: "SBI",
    model: "Flexiheat",
    type: "Wood Stove",
    fileName: "SBI_Flexiheat_Manual.pdf",
    pages: 38,
    uploadDate: "2024-11-15",
    category: "Wood Stoves",
  },
  
  // Mont
  {
    id: "mt-001",
    brand: "Mont",
    model: "Deluxe",
    type: "Wood Stove",
    fileName: "Mont_Deluxe_Manual.pdf",
    pages: 34,
    uploadDate: "2024-11-10",
    category: "Wood Stoves",
  },
  {
    id: "mt-002",
    brand: "Mont",
    model: "Enchantment",
    type: "Wood Stove",
    fileName: "Mont_Enchantment_Manual.pdf",
    pages: 36,
    uploadDate: "2024-11-10",
    category: "Wood Stoves",
  },
  {
    id: "mt-003",
    brand: "Mont",
    model: "Excalibur",
    type: "Wood Stove",
    fileName: "Mont_Excalibur_Manual.pdf",
    pages: 38,
    uploadDate: "2024-11-10",
    category: "Wood Stoves",
  },
  
  // Empire
  {
    id: "e-001",
    brand: "Empire",
    model: "Vail",
    type: "Gas Fireplace",
    fileName: "Empire_Vail_Manual.pdf",
    pages: 42,
    uploadDate: "2024-11-05",
    category: "Gas Fireplaces",
  },
  {
    id: "e-002",
    brand: "Empire",
    model: "Alta",
    type: "Gas Fireplace",
    fileName: "Empire_Alta_Manual.pdf",
    pages: 44,
    uploadDate: "2024-11-05",
    category: "Gas Fireplaces",
  },
  {
    id: "e-003",
    brand: "Empire",
    model: "DVC",
    type: "Direct Vent Fireplace",
    fileName: "Empire_DVC_Manual.pdf",
    pages: 40,
    uploadDate: "2024-11-05",
    category: "Direct Vent",
  },
  {
    id: "e-004",
    brand: "Empire",
    model: "Palisade",
    type: "Gas Fireplace",
    fileName: "Empire_Palisade_Manual.pdf",
    pages: 46,
    uploadDate: "2024-11-05",
    category: "Gas Fireplaces",
  },
  
  // SimpliFire
  {
    id: "sf-001",
    brand: "SimpliFire",
    model: "Allusion",
    type: "Electric Fireplace",
    fileName: "SimpliFire_Allusion_Manual.pdf",
    pages: 26,
    uploadDate: "2024-10-30",
    category: "Electric",
  },
  {
    id: "sf-002",
    brand: "SimpliFire",
    model: "Scorpius",
    type: "Electric Fireplace",
    fileName: "SimpliFire_Scorpius_Manual.pdf",
    pages: 24,
    uploadDate: "2024-10-30",
    category: "Electric",
  },
  {
    id: "sf-003",
    brand: "SimpliFire",
    model: "Vortex",
    type: "Electric Fireplace",
    fileName: "SimpliFire_Vortex_Manual.pdf",
    pages: 28,
    uploadDate: "2024-10-30",
    category: "Electric",
  },
  {
    id: "sf-004",
    brand: "SimpliFire",
    model: "Motion",
    type: "Electric Fireplace",
    fileName: "SimpliFire_Motion_Manual.pdf",
    pages: 26,
    uploadDate: "2024-10-30",
    category: "Electric",
  },
  
  // Modern Flames
  {
    id: "mf-001",
    brand: "Modern Flames",
    model: "Aurora",
    type: "Electric Fireplace",
    fileName: "ModernFlames_Aurora_Manual.pdf",
    pages: 24,
    uploadDate: "2024-10-25",
    category: "Electric",
  },
  {
    id: "mf-002",
    brand: "Modern Flames",
    model: "Landscape Pro",
    type: "Electric Fireplace",
    fileName: "ModernFlames_LandscapePro_Manual.pdf",
    pages: 28,
    uploadDate: "2024-10-25",
    category: "Electric",
  },
  {
    id: "mf-003",
    brand: "Modern Flames",
    model: "Wildland",
    type: "Electric Fireplace",
    fileName: "ModernFlames_Wildland_Manual.pdf",
    pages: 22,
    uploadDate: "2024-10-25",
    category: "Electric",
  },
  
  // American Fireglass
  {
    id: "afg-001",
    brand: "American Fireglass",
    model: "Burner Systems",
    type: "Glass Fireplace",
    fileName: "AFG_BurnerSystems_Manual.pdf",
    pages: 20,
    uploadDate: "2024-10-20",
    category: "Gas Burners",
  },
  {
    id: "afg-002",
    brand: "American Fireglass",
    model: "Fireballs",
    type: "Decorative Media",
    fileName: "AFG_Fireballs_Manual.pdf",
    pages: 16,
    uploadDate: "2024-10-20",
    category: "Decorative",
  },
  {
    id: "afg-003",
    brand: "American Fireglass",
    model: "Fireplace Logs",
    type: "Ceramic Logs",
    fileName: "AFG_FireplaceLogs_Manual.pdf",
    pages: 18,
    uploadDate: "2024-10-20",
    category: "Decorative",
  },
  
  // Rinnai
  {
    id: "rin-001",
    brand: "Rinnai",
    model: "Enclaves",
    type: "Direct Vent Fireplace",
    fileName: "Rinnai_Enclaves_Manual.pdf",
    pages: 44,
    uploadDate: "2024-10-15",
    category: "Direct Vent",
  },
  {
    id: "rin-002",
    brand: "Rinnai",
    model: "EnergySaver",
    type: "Direct Vent Fireplace",
    fileName: "Rinnai_EnergySaver_Manual.pdf",
    pages: 40,
    uploadDate: "2024-10-15",
    category: "Direct Vent",
  },
  {
    id: "rin-003",
    brand: "Rinnai",
    model: "Contour",
    type: "Direct Vent Fireplace",
    fileName: "Rinnai_Contour_Manual.pdf",
    pages: 42,
    uploadDate: "2024-10-15",
    category: "Direct Vent",
  },
  
  // Lennox
  {
    id: "len-001",
    brand: "Lennox",
    model: "Merritt",
    type: "Gas Fireplace",
    fileName: "Lennox_Merritt_Manual.pdf",
    pages: 46,
    uploadDate: "2024-10-10",
    category: "Gas Fireplaces",
  },
  {
    id: "len-002",
    brand: "Lennox",
    model: "Brockway",
    type: "Gas Fireplace",
    fileName: "Lennox_Brockway_Manual.pdf",
    pages: 44,
    uploadDate: "2024-10-10",
    category: "Gas Fireplaces",
  },
  {
    id: "len-003",
    brand: "Lennox",
    model: "Whitby",
    type: "Gas Fireplace",
    fileName: "Lennox_Whitby_Manual.pdf",
    pages: 48,
    uploadDate: "2024-10-10",
    category: "Gas Fireplaces",
  },
  
  // Superior
  {
    id: "sup-001",
    brand: "Superior",
    model: "DRT",
    type: "Direct Vent Fireplace",
    fileName: "Superior_DRT_Manual.pdf",
    pages: 42,
    uploadDate: "2024-10-05",
    category: "Direct Vent",
  },
  {
    id: "sup-002",
    brand: "Superior",
    model: "DRL",
    type: "Direct Vent Linear Fireplace",
    fileName: "Superior_DRL_Manual.pdf",
    pages: 44,
    uploadDate: "2024-10-05",
    category: "Direct Vent",
  },
  {
    id: "sup-003",
    brand: "Superior",
    model: "XTR",
    type: "Wood Burning Fireplace",
    fileName: "Superior_XTR_Manual.pdf",
    pages: 38,
    uploadDate: "2024-10-05",
    category: "Wood Fireplaces",
  },
  
  // Kozy Heat
  {
    id: "kz-001",
    brand: "Kozy Heat",
    model: "Taylor",
    type: "Gas Fireplace",
    fileName: "KozyHeat_Taylor_Manual.pdf",
    pages: 40,
    uploadDate: "2024-09-30",
    category: "Gas Fireplaces",
  },
  {
    id: "kz-002",
    brand: "Kozy Heat",
    model: "Spartan",
    type: "Gas Fireplace",
    fileName: "KozyHeat_Spartan_Manual.pdf",
    pages: 42,
    uploadDate: "2024-09-30",
    category: "Gas Fireplaces",
  },
  {
    id: "kz-003",
    brand: "Kozy Heat",
    model: "Bayport",
    type: "Gas Fireplace",
    fileName: "KozyHeat_Bayport_Manual.pdf",
    pages: 38,
    uploadDate: "2024-09-30",
    category: "Gas Fireplaces",
  },
];

interface Manual {
  id: string;
  brand: string;
  model: string;
  type: string;
  fileName: string;
  url?: string; // URL to manufacturer manual
  pages: number;
  uploadDate: string;
  category: string;
}

// GET - Fetch all manuals
export async function GET() {
  return NextResponse.json(manuals);
}

// POST - Add a new manual
export async function POST(request: Request) {
  try {
    const body = await request.json();
    
    const newManual: Manual = {
      id: `manual-${Date.now()}`,
      brand: body.brand,
      model: body.model,
      type: body.type,
      fileName: body.fileName,
      pages: body.pages || Math.floor(Math.random() * 50) + 10,
      uploadDate: new Date().toISOString().split("T")[0],
      category: body.category,
    };
    
    manuals = [newManual, ...manuals];
    
    return NextResponse.json(newManual, { status: 201 });
  } catch (error) {
    return NextResponse.json(
      { error: "Failed to create manual" },
      { status: 500 }
    );
  }
}
